package com.example.authenticateservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class AuthenticateServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(AuthenticateServiceApplication.class, args);
        System.out.println("""
                MMMMMMMMMMMMWNK0KNNXKXNNNMWXXXNWWWMWXXNXKXWWNNNWNXNKKNN0xO0KNKO0XNNWMMMMWMMMMMMM
                MMMMMMMMMMMWXXXKXXXXKXNNNNNXNWWWNNNWWNXXNWWNXXNWWNWNXNN0OKNXKX0KWMMWMMMMMMMMMMMM
                MMMMMMMMMMWXXXKKK00KKXXXKXNNNXXNXXXNXKKXNNXKKXXKXXXXNWNXK0KXXKK0XWWWNNNNNWMMWMMM
                MMMMMMMMMMWNWXKKK00KKKK0XXKK0XNXXXKKKKKKK00KXK000K00XNXKKKKKKKKXNWWWWWWWNNNWMMMM
                MMMMMMMMMMMMWX00KK000K00K00K0XXNXKKKKKKKKKKXXXKKKK0KXXXXXK0KXWWMMWWMMMWMMWNXXWMM
                MMMMMMMMMMMMMNKKKK0OOOO0KXX0O00KXNNNXKXXNXNNXXK0KXKKXXXKO00XMMMWNNNNXNWNNWWWXKNW
                MMMMMMMMMMMMMWXKKKKOOOkO0KX0OOO0NWWWXXWNKXXXNKO0XXKXKKK0KXKNMMWKooxlcoooONMWWK0W
                MMMMMMMMMMMMMWNXXXK000OkKX0OOO00KXXXXWMNKXXKXK00KK0KXK0KX0KNMMWKddxxdxkkOKMMMXKW
                MMMMMMMMMMMMMWWWWXKKK0O0XWNKKK00O0NNXWMWWNNWXOk0KKXXK0OXN0OXMMMMW0xkOkxd0WMMMXXM
                MMMMMMMMMMMMMMMMWNNK0OOKNWWWWWWWXKXNWMMMMMWNKKNWWWWX0KXXK0KNMMMMNdoKklx0NMMMMNNM
                MMMMMMMMMMMMMMMMMMWNKK0kKMMMMMMMWWWWMMMMMMMWWWWMMMWNXNN0kOXWMMMW0xOKkkKXNMMMMNNM
                MMMMMMMMMMMMMMMMWMMWNNWK0NMMMMMMMWMMMMMMWMMMMMMMMMMWWW0kO0KNMMM0l:cooc:oONMMMXXW
                MMMMMMMMMMMMMMWWMWMMMMMW0KMMMMMMMMMMMMMMMMMMMMMMMMMMWKO0XNXKWMMXOOO0O000KNMMWXNM
                MMMMMMMMMMMMMMWWMMMMMMMMX0NMMMMMMMMMWWWMWWMMMMMMMMMMKOXNWMWNWWMWWMMMWWMMMMMWXNWM
                MMMMMMMMMMMMMMMMMMMMMMMMWkkNMMMMMMMMWNWWWWMMMMMMMWWXdkMMMMMMWWWWNNNWMWWWWNKKNWWM
                MMMMMMMMMMMMMMMMMMMMMMMMMOd0NWMWWWWNNNXNNNNNWWXNWNXOxKMMMMMMWWWWWXOKWWWWWWXNWMMM
                MMMMMMMMMMMMMMMMMMMMMMMMM0kKXXNWWWXkxxxxkkOKWWNXXNXxOWMMMMMMMWMMWNNWMMMMMMMMMMMM
                MMMMMMMMMMMMMMMMMWMMMMMWMK0WWNKKWMMNNXXXNNWWWNXXNNOxKMWMMMMMMMMMWWWMMMMMMMMMMMMM
                MMMMMMMMMMMMMMMMMMMMMMWXOlxNNWXOOXNWMMMMMMWX00NMWW0kXMMMMMMMMMMMMMMMMMMMMMMMMMMM
                MMMMMMMMMMMMMMMMWMMWKxc'. cNK0NXO00KXKKKK0kkKNWWWWk;o0NWMMMMMMMMMMMMMMMMMMMMMMMM
                MMMMMMMMMMMMMMMWKxl,.     .o00KWNKXXXXXKKOONWXKNMWl  .,lONWMMMMMMMMMMMMMMMMMMMMM
                MMMMMMMMMMNKOdl;.           .cxKWNK0KXWNXKXX00KX0o.      ':lkKWMMMMMMMMMMMMMMMMM
                MMMMMMMMXkc'      ..          .c0WXKKXWNXNXOOOxc.            'oKWMMMMMMMMMMMMMMM
                """);
    }

}
